repos:
    -  repo: https://github.com/pycqa/isort
       rev: 5.10.1
       hooks:
       - id: isort

    -   repo: https://github.com/psf/black
        rev: 22.6.0
        hooks:
        - id: black
          language_version: python3.7

        # Refer https://github.com/pre-commit/pre-commit/issues/1206#issuecomment-551000892
    -   repo: https://gitlab.com/pycqa/flake8.git
        rev: 3.9.2
        hooks:
        - id: flake8
    
    -   repo: https://github.com/python-poetry/poetry
        rev: 1.2.0
        hooks:
        - id: poetry-check